// Generated by scripts/commands.py from src/shared/commands.json.
// Edit the JSON and re-run the script; changes here are overwritten.

package org.switchboard.android.irc

/**
 * Every slash command, with what it takes and what it does.
 *
 * The desktop imports `src/shared/commands.json` directly and this is the
 * same list, carried over so that `/help` answers the same on both. A test
 * on the desktop holds the catalogue to the switch that runs them, so a
 * command that exists and is not named here fails there.
 */
object CommandList {

    data class Entry(
        val name: String,
        val aliases: List<String> = emptyList(),
        val usage: String? = null,
        val summary: String,
        /** Only meaningful with a channel open */
        val channel: Boolean = false
    )

    val COMMANDS: List<Entry> = listOf(
        Entry(name = "me", usage = "<action>", summary = "Say what you are doing, in the third person"),
        Entry(name = "say", usage = "<message>", summary = "Send a message that begins with a slash"),
        Entry(name = "msg", aliases = listOf("query"), usage = "<nick|#channel> <message>", summary = "Message somebody without opening a conversation"),
        Entry(name = "notice", usage = "<target> <message>", summary = "Send a notice, which clients are not meant to answer"),
        Entry(name = "ctcp", usage = "<nick> <VERSION|PING|TIME|…>", summary = "Ask a client about itself"),
        Entry(name = "dcc", usage = "send <nick>", summary = "Offer somebody a file directly"),
        Entry(name = "join", aliases = listOf("j"), usage = "#channel [key]", summary = "Go into a channel"),
        Entry(name = "part", aliases = listOf("leave"), usage = "[#channel] [reason]", summary = "Leave a channel"),
        Entry(name = "cycle", aliases = listOf("hop"), usage = "[#channel]", summary = "Leave a channel and come straight back"),
        Entry(name = "knock", usage = "<#channel> [reason]", summary = "Ask to be let into an invite-only channel"),
        Entry(name = "topic", usage = "[#channel] [new topic]", summary = "Read or set a channel's topic", channel = true),
        Entry(name = "invite", usage = "<nick> [#channel]", summary = "Invite somebody in", channel = true),
        Entry(name = "names", usage = "[#channel]", summary = "Ask who is in a channel", channel = true),
        Entry(name = "list", usage = "[pattern]", summary = "Browse the channels on this network"),
        Entry(name = "mode", usage = "<target> <modes>", summary = "Set modes by hand"),
        Entry(name = "voice", usage = "[nick…]", summary = "Let somebody speak in a moderated channel", channel = true),
        Entry(name = "devoice", usage = "[nick…]", summary = "Take somebody’s voice away", channel = true),
        Entry(name = "halfop", usage = "[nick…]", summary = "Make somebody a half-operator", channel = true),
        Entry(name = "dehalfop", usage = "[nick…]", summary = "Remove somebody’s half-operator", channel = true),
        Entry(name = "op", usage = "[nick…]", summary = "Make somebody a channel operator", channel = true),
        Entry(name = "deop", usage = "[nick…]", summary = "Remove somebody’s operator", channel = true),
        Entry(name = "admin", usage = "[nick…]", summary = "Make somebody a channel admin, where the network has them", channel = true),
        Entry(name = "deadmin", usage = "[nick…]", summary = "Remove somebody’s admin", channel = true),
        Entry(name = "founder", aliases = listOf("owner"), usage = "[nick…]", summary = "Hand somebody the channel, where the network has founders", channel = true),
        Entry(name = "defounder", aliases = listOf("deowner"), usage = "[nick…]", summary = "Take the founder rank back", channel = true),
        Entry(name = "kick", usage = "<nick> [reason]", summary = "Put somebody out of the channel", channel = true),
        Entry(name = "ban", usage = "<nick or mask>", summary = "Keep somebody out", channel = true),
        Entry(name = "unban", usage = "<nick or mask>", summary = "Let them back in", channel = true),
        Entry(name = "kickban", usage = "<nick> [reason]", summary = "Ban and then kick, in that order", channel = true),
        Entry(name = "quiet", usage = "<nick or mask>", summary = "Let somebody stay but not speak, where the network allows it", channel = true),
        Entry(name = "unquiet", usage = "<nick or mask>", summary = "Let them speak again", channel = true),
        Entry(name = "banlist", aliases = listOf("bans"), usage = "[#channel]", summary = "Show who is banned", channel = true),
        Entry(name = "whois", usage = "<nick>", summary = "Ask the network about somebody"),
        Entry(name = "whowas", usage = "<nick> [count]", summary = "Ask about somebody who has left"),
        Entry(name = "who", usage = "<nick, #channel or mask>", summary = "Ask about everybody matching"),
        Entry(name = "ignore", usage = "<nick or mask>", summary = "Stop hearing from somebody, on this client"),
        Entry(name = "unignore", usage = "<nick or mask>", summary = "Hear from them again"),
        Entry(name = "nick", usage = "<nickname>", summary = "Change your nick"),
        Entry(name = "setname", usage = "<real name>", summary = "Change your real name without reconnecting"),
        Entry(name = "away", usage = "[reason]", summary = "Say you have stepped away"),
        Entry(name = "back", summary = "Say you are back"),
        Entry(name = "oper", usage = "<name> <password>", summary = "Become a network operator"),
        Entry(name = "quit", usage = "[reason]", summary = "Leave the network"),
        Entry(name = "nickserv", aliases = listOf("ns"), usage = "<command> [arguments]", summary = "Talk to NickServ"),
        Entry(name = "chanserv", aliases = listOf("cs"), usage = "<command> [arguments]", summary = "Talk to ChanServ"),
        Entry(name = "motd", summary = "Read the message of the day"),
        Entry(name = "lusers", summary = "How many people are on this network"),
        Entry(name = "time", summary = "Ask the server what time it is"),
        Entry(name = "version", summary = "Ask what the server is running"),
        Entry(name = "links", summary = "List the servers on this network"),
        Entry(name = "stats", usage = "[letter]", summary = "Ask the server for a statistic"),
        Entry(name = "info", summary = "Ask the server about itself"),
        Entry(name = "admininfo", summary = "Who runs this server"),
        Entry(name = "wallops", usage = "<message>", summary = "Message every operator, if you are one"),
        Entry(name = "ping", usage = "[target]", summary = "Measure the round trip"),
        Entry(name = "help", usage = "[command]", summary = "List what you can type, or explain one command"),
        Entry(name = "clear", summary = "Empty this conversation from the screen"),
        Entry(name = "raw", aliases = listOf("quote"), usage = "<IRC line>", summary = "Send a line to the server exactly as typed"),
    )

    /** Every name and alias, sorted — what a completion list offers */
    fun names(): List<String> =
        COMMANDS.flatMap { listOf(it.name) + it.aliases }.sorted()

    /** The entry for a name or one of its aliases */
    fun find(name: String): Entry? {
        val wanted = name.trim().removePrefix("/").lowercase()
        return COMMANDS.firstOrNull { it.name == wanted || wanted in it.aliases }
    }

    /** One command as a line: `/kick <nick> [reason] — put somebody out` */
    fun line(command: Entry): String {
        val names = (listOf(command.name) + command.aliases).joinToString(", ") { "/$it" }
        val usage = command.usage?.let { " $it" } ?: ""
        return "$names$usage — ${command.summary}"
    }

    /**
     * What `/help` prints: one command when asked about one, all of them
     * otherwise — which is long, and is the point.
     */
    fun help(query: String?): List<String> {
        val wanted = (query ?: "").trim()
        if (wanted.isEmpty()) return COMMANDS.map { line(it) }
        val found = find(wanted)
        return listOf(
            if (found != null) line(found)
            else "No command called /${wanted.removePrefix("/")}. Type /help for the list."
        )
    }
}
