import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import { COMMANDS, commandNames, findCommand, helpLines } from '@shared/commandlist'

/**
 * The catalogue and the switch that runs them, held together.
 *
 * The client answered sixty-odd commands and offered seventeen of them in the
 * composer's completion list. `/ban`, `/kickban`, `/cycle`, `/knock` and the
 * rest worked perfectly and were findable only by already knowing they were
 * there — because the completion list was a second list, written by hand, and
 * it fell behind the moment anybody added a command.
 *
 * So the catalogue is read out of the source here rather than trusted. A
 * command the client handles and the catalogue does not name fails; a
 * catalogue entry nothing handles fails too, which is the half that catches a
 * typo in a name somebody will one day put in the completion list.
 */
const source = readFileSync(join(__dirname, '../../src/main/irc/commands.ts'), 'utf8')

/** Every `case 'x':` in the command switch */
const handled = new Set(
  [...source.matchAll(/^\s*case '([a-z]+)':/gm)].map((match) => match[1])
)

describe('every command the client answers', () => {
  it('is in the catalogue', () => {
    const named = new Set(commandNames())
    const missing = [...handled].filter((name) => !named.has(name)).sort()

    expect(
      missing,
      'These run but nothing offers them. Add them to src/shared/commandlist.ts.'
    ).toEqual([])
  })

  it('and nothing in the catalogue is made up', () => {
    const invented = commandNames().filter((name) => !handled.has(name))

    expect(
      invented,
      'These are offered but `runCommand` has no case for them.'
    ).toEqual([])
  })

  it('covers a good deal more than the composer used to offer', () => {
    // The list this replaced had seventeen names in it
    expect(commandNames().length).toBeGreaterThan(50)
  })
})

describe('the catalogue itself', () => {
  it('says something about each one', () => {
    for (const command of COMMANDS) {
      expect(command.summary.length, `/${command.name} needs a summary`).toBeGreaterThan(8)
      // A summary is a line, not a paragraph
      expect(command.summary).not.toContain('\n')
    }
  })

  it('names each command once', () => {
    const names = commandNames()
    expect(names.length, `duplicated: ${names.filter((n, at) => names.indexOf(n) !== at)}`).toBe(
      new Set(names).size
    )
  })

  it('finds a command by either of its names', () => {
    expect(findCommand('founder')?.name).toBe('founder')
    expect(findCommand('owner')?.name).toBe('founder')
    expect(findCommand('/owner')?.name).toBe('founder')
    expect(findCommand('OWNER')?.name).toBe('founder')
    expect(findCommand('nonsense')).toBe(null)
  })
})

describe('what /help prints', () => {
  it('is the whole list when asked for nothing', () => {
    expect(helpLines()).toHaveLength(COMMANDS.length)
    expect(helpLines()[0]).toMatch(/^\/me /)
  })

  it('is one line when asked about one command', () => {
    expect(helpLines('kick')).toEqual(['/kick <nick> [reason] — Put somebody out of the channel'])
  })

  it('shows both names where a command has two', () => {
    expect(helpLines('owner')[0]).toContain('/founder, /owner')
  })

  it('says so rather than nothing when there is no such command', () => {
    expect(helpLines('flarp')[0]).toBe('No command called /flarp. Type /help for the list.')
  })
})

/**
 * And the copy the phone compiles in.
 *
 * `scripts/commands.py` writes it out of the same JSON, the way
 * `scripts/themes.py` writes the palettes. This is what catches somebody
 * editing the catalogue and not re-running the script — the two clients
 * answering `/help` with two different lists is two products.
 */
describe('the list the phone was given', () => {
  const kotlin = readFileSync(
    join(__dirname, '../../android/app/src/main/java/org/switchboard/android/irc/CommandList.kt'),
    'utf8'
  )

  it('names the same commands, in the same order', () => {
    const carried = [...kotlin.matchAll(/Entry\(name = "([^"]+)"/g)].map((m) => m[1])
    expect(carried).toEqual(COMMANDS.map((c) => c.name))
  })

  it('carries the aliases too', () => {
    for (const command of COMMANDS) {
      if (!command.aliases) continue
      const spelled = command.aliases.map((a) => `"${a}"`).join(', ')
      expect(kotlin, `/${command.name} aliases`).toContain(`aliases = listOf(${spelled})`)
    }
  })

  it('says it is generated, so nobody edits it by hand', () => {
    expect(kotlin.startsWith('// Generated by scripts/commands.py')).toBe(true)
  })
})
