#!/usr/bin/env python3
"""
Build the Android launcher icon from the desktop's artwork.

`resources/icon.svg` is the one drawing of the Switchboard mark. The desktop
uses it directly; Android needs it cut into an adaptive icon — a background
layer, a foreground layer inset into the mask's safe zone, and a monochrome
layer the system recolours for themed icons — plus flat bitmaps for anything
that still asks for one.

Doing that by hand means the two marks drift. Run this instead:

    python3 scripts/android-icon.py

Requires cairosvg (pip install cairosvg).
"""

import io
import pathlib
import re
import sys

try:
    import cairosvg
except ImportError:
    sys.exit('cairosvg is needed: pip install cairosvg')

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'resources/icon.svg'
RES = ROOT / 'android/app/src/main/res'

# The adaptive canvas is 108dp, of which a launcher shows the inner 72dp. The
# mark is wider than it is tall, so what matters is its diagonal: at 758x588 the
# widest that fits a 72dp circle is 56.9dp. 54 leaves a little air, and was
# checked against both the circle and the rounded-square mask.
GLYPH_DP = 54.0

# The darkest colour in the app's own palette rather than pure black, so the
# icon still reads as a shape against a black wallpaper.
BACKGROUND = '#11111B'

DENSITIES = (('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192))

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- {note}
     Generated by scripts/android-icon.py from resources/icon.svg, the same
     drawing the desktop uses. Re-run that script; do not edit the path here. -->"""


def artwork() -> tuple[str, float, float]:
    """The glyph's path, and the transform that lands it in a 108dp canvas."""
    svg = SOURCE.read_text()
    match = re.search(r'<path[^>]*\bd="([^"]+)"', svg)
    if not match:
        sys.exit(f'{SOURCE}: no <path> to work with')
    path = match.group(1).strip()

    # Measure rather than assume: the mark is wider than it is tall, and its
    # width is what the mask threatens.
    alone = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" '
        f'width="1024" height="1024"><path fill="#fff" d="{path}"/></svg>'
    )
    from PIL import Image
    rendered = Image.open(io.BytesIO(cairosvg.svg2png(bytestring=alone.encode())))
    box = rendered.getbbox()
    if not box:
        sys.exit(f'{SOURCE}: the path draws nothing')

    left, top, right, bottom = box
    scale = GLYPH_DP / (right - left)
    # Centre whatever the artwork's own centre happens to be
    offset_x = 54 - ((left + right) / 2) * scale
    offset_y = 54 - ((top + bottom) / 2) * scale
    return path, scale, (offset_x, offset_y)


def vector(name: str, size: int, scale: float, offset: tuple[float, float],
           tint: str, note: str, path: str) -> None:
    (RES / 'drawable').mkdir(parents=True, exist_ok=True)
    (RES / 'drawable' / f'{name}.xml').write_text(
        HEADER.format(note=note) + f'''
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{size}"
    android:viewportHeight="{size}">
    <group
        android:scaleX="{scale:.6f}"
        android:scaleY="{scale:.6f}"
        android:translateX="{offset[0]:.4f}"
        android:translateY="{offset[1]:.4f}">
        <path
            android:fillColor="{tint}"
            android:pathData="{path}" />
    </group>
</vector>
''')


def main() -> None:
    path, scale, offset = artwork()

    vector('ic_launcher_foreground', 108, scale, offset, '#FFFFFF',
           "The launcher icon's foreground layer.", path)
    vector('ic_launcher_monochrome', 108, scale, offset, '#FFFFFF',
           'The themed-icon layer, which the system recolours to the wallpaper.', path)

    # The status bar draws its icons as a silhouette, so this one is barely
    # inset — there is no mask to keep clear of, only a 24dp square to fill.
    span = GLYPH_DP / scale                              # the glyph, in artwork units
    centre = ((54 - offset[0]) / scale, (54 - offset[1]) / scale)
    notif_scale = 22.0 / span
    notif_offset = (12 - centre[0] * notif_scale, 12 - centre[1] * notif_scale)
    vector('ic_notification', 24, notif_scale, notif_offset, '#FFFFFF',
           'The status-bar icon. Android draws it as a silhouette; only shape carries.', path)

    (RES / 'values').mkdir(parents=True, exist_ok=True)
    (RES / 'values' / 'colors.xml').write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- The icon's background layer. The darkest colour in the app's own
         palette rather than pure black, so the icon still reads as a shape on a
         black wallpaper. -->
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
''')

    (RES / 'mipmap-anydpi-v26').mkdir(parents=True, exist_ok=True)
    for name in ('ic_launcher', 'ic_launcher_round'):
        (RES / 'mipmap-anydpi-v26' / f'{name}.xml').write_text(
            '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-icon.py -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
''')

    flat = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="108" height="108">
  <rect width="108" height="108" rx="24" fill="{BACKGROUND}"/>
  <g transform="translate({offset[0]},{offset[1]}) scale({scale})">
    <path fill="#ffffff" d="{path}"/>
  </g>
</svg>'''

    for density, px in DENSITIES:
        folder = RES / f'mipmap-{density}'
        folder.mkdir(parents=True, exist_ok=True)
        png = cairosvg.svg2png(bytestring=flat.encode(), output_width=px, output_height=px)
        (folder / 'ic_launcher.png').write_bytes(png)
        (folder / 'ic_launcher_round.png').write_bytes(png)

    print(f'icon written: glyph {GLYPH_DP}dp wide in a 108dp canvas '
          f'(scale {scale:.6f}, offset {offset[0]:.2f},{offset[1]:.2f})')


if __name__ == '__main__':
    main()
