#!/usr/bin/env python3
"""
Carry the slash command catalogue over to the phone.

`src/shared/commands.json` is the source of truth: the desktop imports it
directly, and the phone cannot, so this writes the same list out as Kotlin.
The same arrangement as `scripts/themes.py` and for the same reason — two
clients answering `/help` with two different lists is two products.

Run it after adding or changing a command:

    python3 scripts/commands.py

The tests fail if you forget, which is the point.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / 'src/shared/commands.json'
KOTLIN = ROOT / 'android/app/src/main/java/org/switchboard/android/irc/CommandList.kt'


def kotlin(commands: list) -> str:
    def quote(text: str) -> str:
        return '"' + text.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$') + '"'

    lines = [
        '// Generated by scripts/commands.py from src/shared/commands.json.',
        '// Edit the JSON and re-run the script; changes here are overwritten.',
        '',
        'package org.switchboard.android.irc',
        '',
        '/**',
        ' * Every slash command, with what it takes and what it does.',
        ' *',
        ' * The desktop imports `src/shared/commands.json` directly and this is the',
        ' * same list, carried over so that `/help` answers the same on both. A test',
        ' * on the desktop holds the catalogue to the switch that runs them, so a',
        ' * command that exists and is not named here fails there.',
        ' */',
        'object CommandList {',
        '',
        '    data class Entry(',
        '        val name: String,',
        '        val aliases: List<String> = emptyList(),',
        '        val usage: String? = null,',
        '        val summary: String,',
        '        /** Only meaningful with a channel open */',
        '        val channel: Boolean = false',
        '    )',
        '',
        '    val COMMANDS: List<Entry> = listOf(',
    ]

    for command in commands:
        parts = [f'name = {quote(command["name"])}']
        if command.get('aliases'):
            spelled = ', '.join(quote(a) for a in command['aliases'])
            parts.append(f'aliases = listOf({spelled})')
        if command.get('usage'):
            parts.append(f'usage = {quote(command["usage"])}')
        parts.append(f'summary = {quote(command["summary"])}')
        if command.get('channel'):
            parts.append('channel = true')
        lines.append('        Entry(' + ', '.join(parts) + '),')

    lines += [
        '    )',
        '',
        '    /** Every name and alias, sorted — what a completion list offers */',
        '    fun names(): List<String> =',
        '        COMMANDS.flatMap { listOf(it.name) + it.aliases }.sorted()',
        '',
        '    /** The entry for a name or one of its aliases */',
        '    fun find(name: String): Entry? {',
        '        val wanted = name.trim().removePrefix("/").lowercase()',
        '        return COMMANDS.firstOrNull { it.name == wanted || wanted in it.aliases }',
        '    }',
        '',
        '    /** One command as a line: `/kick <nick> [reason] — put somebody out` */',
        '    fun line(command: Entry): String {',
        '        val names = (listOf(command.name) + command.aliases).joinToString(", ") { "/$it" }',
        '        val usage = command.usage?.let { " $it" } ?: ""',
        '        return "$names$usage — ${command.summary}"',
        '    }',
        '',
        '    /**',
        '     * What `/help` prints: one command when asked about one, all of them',
        '     * otherwise — which is long, and is the point.',
        '     */',
        '    fun help(query: String?): List<String> {',
        '        val wanted = (query ?: "").trim()',
        '        if (wanted.isEmpty()) return COMMANDS.map { line(it) }',
        '        val found = find(wanted)',
        '        return listOf(',
        '            if (found != null) line(found)',
        '            else "No command called /${wanted.removePrefix("/")}. Type /help for the list."',
        '        )',
        '    }',
        '}',
        '',
    ]
    return '\n'.join(lines)


def main() -> None:
    commands = json.loads(DATA.read_text())['commands']
    KOTLIN.write_text(kotlin(commands))
    print(f'{len(commands)} commands → {KOTLIN.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
