#!/usr/bin/env python3
"""
Carry the desktop's themes over to the phone.

`src/renderer/styles/globals.css` is the source of truth: it is where a theme is
written, and CSS is what the desktop actually paints with. The phone cannot read
CSS, so this reads those blocks and writes two things — a fixture both test
suites check against, and the Kotlin the Android app compiles in.

Run it after adding or changing a theme:

    python3 scripts/themes.py

The tests fail if you forget, which is the point.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = ROOT / 'src/renderer/styles/globals.css'
FIXTURE = ROOT / 'tests/fixtures/themes.json'
KOTLIN = ROOT / 'android/app/src/main/java/org/switchboard/android/ui/Palettes.kt'

# The order the picker offers them in, and the names a person would recognise
LABELS = {
    'catppuccin-mocha': 'Catppuccin Mocha',
    'catppuccin-latte': 'Catppuccin Latte',
    'catppuccin-frappe': 'Catppuccin Frappé',
    'catppuccin-macchiato': 'Catppuccin Macchiato',
    'dracula': 'Dracula',
    'nord': 'Nord',
    'gruvbox': 'Gruvbox',
    'one-dark': 'One Dark',
    'rose-pine': 'Rosé Pine',
    'solarized-dark': 'Solarized Dark',
    'tokyo-night': 'Tokyo Night',
    'kanagawa': 'Kanagawa',
    'discord': 'Discord',
}

# What the phone paints with, named for the surface rather than the shade.
# Tailwind's scale is the desktop's vocabulary; these are the same colours under
# names that mean something away from a utility-class stylesheet.
ROLES = {
    'crust': 'gray-950',
    'mantle': 'gray-900',
    'base': 'gray-800',
    'surface0': 'gray-700',
    'surface1': 'gray-600',
    'muted': 'gray-500',
    'overlay': 'gray-400',
    'subtext': 'gray-300',
    'text': 'gray-100',
    'accent': 'indigo-500',
    'accentSoft': 'indigo-400',
    'good': 'green-400',
    'warn': 'yellow-500',
    'bad': 'red-400',
}

# Avatar colours: Tailwind's own -600 shades, which no theme overrides — except
# green and indigo, which every theme does, so those two follow the theme on the
# desktop and have to here as well.
FIXED_AVATARS = {
    'red': '#e7000b', 'orange': '#f54900', 'amber': '#e17100', 'yellow': '#d08700',
    'lime': '#5ea500', 'emerald': '#009966', 'teal': '#009689', 'cyan': '#0092b8',
    'sky': '#0084d1', 'blue': '#155dfc', 'violet': '#7f22fe', 'purple': '#9810fa',
    'fuchsia': '#c800de', 'pink': '#e60076', 'rose': '#ec003f',
}
AVATAR_ORDER = [
    'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal',
    'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
]

DEFAULT = 'catppuccin-mocha'


def variables(block: str) -> dict:
    return dict(re.findall(r'--color-([\w-]+):\s*([^;]+);', block))


def read_palettes() -> dict:
    css = CSS.read_text()

    # The default theme has no [data-theme] of its own — it is the bare :root
    mocha = re.search(r'Catppuccin Mocha.*?\n:root \{(.*?)\n\}', css, re.S)
    if not mocha:
        sys.exit(f'{CSS}: could not find the default palette')

    palettes = {DEFAULT: variables(mocha.group(1))}
    for name, block in re.findall(r"\[data-theme='([\w-]+)'\] \{(.*?)\n\}", css, re.S):
        palettes[name] = variables(block)
    return palettes


def build() -> dict:
    palettes = read_palettes()

    unnamed = set(palettes) - set(LABELS)
    if unnamed:
        sys.exit(f'{CSS} defines {sorted(unnamed)} — add them to LABELS in this script')
    unstyled = set(LABELS) - set(palettes)
    if unstyled:
        sys.exit(f'{sorted(unstyled)} are offered but have no palette in {CSS}')

    themes = []
    for name, label in LABELS.items():
        tokens = palettes[name]
        roles = {}
        for role, token in ROLES.items():
            if token not in tokens:
                sys.exit(f"theme '{name}' is missing --color-{token}")
            roles[role] = tokens[token].strip().lower()

        avatars = []
        for colour in AVATAR_ORDER:
            if colour in ('green', 'indigo'):
                avatars.append(tokens[f'{colour}-600'].strip().lower())
            else:
                avatars.append(FIXED_AVATARS[colour])

        themes.append({'id': name, 'label': label, 'roles': roles, 'avatars': avatars})

    return {
        'note': (
            'The palettes both clients paint with. Generated from '
            'src/renderer/styles/globals.css by scripts/themes.py — edit the CSS '
            'and re-run that, never this file.'
        ),
        'default': DEFAULT,
        'themes': themes,
    }


def kotlin(data: dict) -> str:
    def argb(hex_colour: str) -> str:
        return '0xFF' + hex_colour.lstrip('#').upper()

    lines = [
        '// Generated by scripts/themes.py from src/renderer/styles/globals.css.',
        '// Edit the CSS and re-run the script; changes here are overwritten.',
        '',
        'package org.switchboard.android.ui',
        '',
        'import androidx.compose.ui.graphics.Color',
        '',
        '/**',
        ' * One theme, as a set of colours.',
        ' *',
        ' * The names are roles rather than shades, because a palette that reads',
        ' * "gray-800" tells you nothing about where it belongs on a screen.',
        ' */',
        'data class Palette(',
        '    val id: String,',
        '    val label: String,',
        '    val crust: Color,',
        '    val mantle: Color,',
        '    val base: Color,',
        '    val surface0: Color,',
        '    val surface1: Color,',
        '    val muted: Color,',
        '    val overlay: Color,',
        '    val subtext: Color,',
        '    val text: Color,',
        '    val accent: Color,',
        '    val accentSoft: Color,',
        '    val good: Color,',
        '    val warn: Color,',
        '    val bad: Color,',
        '    /** Avatar colours, in the order the nick hash indexes them */',
        '    val avatars: List<Color>',
        ')',
        '',
        '/** Every theme the desktop offers, in the order it offers them */',
        'val PALETTES: List<Palette> = listOf(',
    ]

    for theme in data['themes']:
        r = theme['roles']
        lines.append('    Palette(')
        lines.append(f'        id = "{theme["id"]}",')
        lines.append(f'        label = "{theme["label"]}",')
        for role in ROLES:
            lines.append(f'        {role} = Color({argb(r[role])}),')
        lines.append('        avatars = listOf(')
        for row in range(0, len(theme['avatars']), 4):
            chunk = theme['avatars'][row:row + 4]
            lines.append('            ' + ' '.join(f'Color({argb(c)}),' for c in chunk))
        lines.append('        )')
        lines.append('    ),')

    lines += [
        ')',
        '',
        f'/** What a device paints with until someone chooses otherwise */',
        f'val DEFAULT_PALETTE: Palette = PALETTES.first {{ it.id == "{data["default"]}" }}',
        '',
        '/** The theme with this id, or the default when it names one we do not have */',
        'fun paletteFor(id: String?): Palette =',
        '    PALETTES.firstOrNull { it.id == id } ?: DEFAULT_PALETTE',
        '',
    ]
    return '\n'.join(lines)


def main() -> None:
    data = build()
    FIXTURE.write_text(json.dumps(data, indent=2) + '\n')
    KOTLIN.write_text(kotlin(data))
    print(f'{len(data["themes"])} themes → {FIXTURE.relative_to(ROOT)}, {KOTLIN.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
